spring:
  application:
    name: spring-cloud-stream
  cloud:
    function:
#      definition: logEventReceived|saveInDBEventReceived;sensorEventProducer
      definition: logEventReceivedSaveInDBEventReceived;sensorEventProducer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
#          kafka-properties: global props
#            boootstrap.server: localhost:9092
          consumerProperties: #consumer props
            max.poll.records: 250
#          producerProperties:
#            boootstrap.server: localhost:9092
      bindings:
        logEventReceivedSaveInDBEventReceived-in-0: #a consumer
          destination: sensor_event_topic
          group: ${spring.application.name}
        sensorEventProducer-out-0: #a producer
          destination: sensor_event_topic
          producer:
            poller: #manage polling for specific supplier producer
              fixed-delay: 5000
              initial-delay: 1000
        sensorEventAnotherProducer-out-0: #another producer
          destination: sensor_event_topic
        sensorEventDlqProducer-out-0: #DLQ producer
          destination: sensor_event_topic_dlq
