name: auto_tag
on:
  push:
    branches:
      - main
jobs:
  tagging-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create tag
        run: |
          tag=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Creating tag $tag"
          git tag -a "v$tag" -m "Release $tag"
          git push origin v$tag